#머신러닝 순서

1.  데이터수집 (feature(변수) , label(정답))
2.  데이터전처리
3.  데이터분류 ( 학습데이터, 테스트데이터)
4.  모델선정
5.  학습
6.  예측

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('appreply.csv')
df.head()

Unnamed: 0                                               text  score
0           0                                                NaN      4
1           1                                                NaN      5
2           2                                                NaN      1
3           3  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
4           4  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5

In [ ]:
df.dropna(inplace=True)
df.reset_index(inplace=True)
df.drop(['index','Unnamed: 0'],axis=1,inplace=True)
df = df.drop_duplicates(subset=['text'])
df.head()

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
df.head()

index                                               text  score
0      0  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
1      1  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
2      2  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
3      3  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
4      4  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3

In [ ]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 60.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 40.2 MB/s eta 0:00:00


In [ ]:
import re
from tqdm import tqdm
from konlpy.tag import Okt

noun_result = []

for temp in tqdm(df['text']):
    temp_result = re.sub(r'[^ㄱ-ㅣ가-힣\s]','',temp)
    okt = Okt()
    temp_nouns = okt.nouns(temp_result)
    temp_noins_result = [x for x in temp_nouns if len(x)>1]
    noun_result.append(temp_noins_result)

noun_result

100%|██████████| 1000/1000 [00:27<00:00, 35.91it/s]


[['배달',
  '민족',
  '주문',
  '리뷰',
  '자주',
  '참고',
  '편입',
  '한가지',
  '건의',
  '사항',
  '최신',
  '점순',
  '주문',
  '자하',
  '메뉴',
  '메뉴',
  '리뷰',
  '확인',
  '기능',
  '메뉴',
  '검색',
  '기능',
  '리뷰',
  '특정',
  '메뉴',
  '검색',
  '기능',
  '주문',
  '수가',
  '메뉴',
  '리뷰',
  '보기',
  '위해',
  '래그',
  '시간',
  '소요',
  '효율',
  '발생',
  '긍정',
  '검토',
  '주심'],
 ['주문',
  '과거',
  '목록',
  '검색',
  '기능',
  '분명',
  '가게',
  '기억',
  '찾기',
  '메뉴',
  '검색',
  '곱창',
  '치면',
  '과거',
  '곱창',
  '목록',
  '가게',
  '리뷰',
  '리뷰',
  '보기'],
 ['검색',
  '화면',
  '전체',
  '배달',
  '포장',
  '배달',
  '크롤',
  '아래',
  '크롤',
  '자꾸만',
  '왼쪽',
  '오른쪽',
  '전체',
  '포장',
  '정말',
  '검색',
  '배달',
  '포장',
  '마트',
  '하나',
  '선택',
  '좌우',
  '가끔',
  '크롤',
  '왼쪽',
  '전체',
  '가게'],
 ['배달',
  '정렬',
  '가게',
  '가장',
  '위로',
  '지역',
  '추가',
  '배달',
  '별도',
  '체크',
  '배달',
  '만원',
  '이상',
  '배달',
  '장난',
  '하나',
  '하나',
  '가격',
  '대별',
  '금액',
  '체크',
  '배달',
  '별도',
  '확인'],
 ['최근',
  '업데이트',
  '안드로이드',
  '사양',
  '정도',
  '배민',
  '어플',
  '실행',
  '업데이트',
  '하라',
  '업데이트',


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(tokenizer=lambda x: x, lowercase=False)
tfidf = tfidf_vect.fit_transform(noun_result).toarray()
tfidf_vect.vocabulary_
tfidf.shape
tfidf

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.19910076, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.07764362, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06728922, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
df['score_real'] = np.where(df['score']>3,1,0)
df

index                                               text  score  \
0        0  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4   
1        1  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5   
2        2  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1   
3        3  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2   
4        4  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3   
..     ...                                                ...    ...   
995    995  갑자기 로그아웃 되더니 비밀번호 변경 실패 메세지가 계속 뜨네요. 휴대폰 번호로 인...      1   
996    996  기사님이 상품 픽업을 하셨는지 표시되면 더 좋을 것 같습니다. 가게에서 조리가 늦게...      3   
997    997  요즘 요기요 보다 배민을 많이 쓰는 사람입니다 전화보다 앱을 써서 좀더 간편하고 다...      3   
998    998  취소 됐으면 적어도 전화 주는 제도는 있어야하는거 아닌가요? 주문해놓고 다른거 하는...      1   
999    999  배달의 민족 참 잘 사용하고 있어요. 별 다섯 개를 드리고 싶지만 한 가지 아쉬운 ...      4   

     score_real  
0             1  
1             1  
2             0  
3             0  
4             0  
..          ...  
995           0  
996           0  
997           0  
998           0  
999           1  

[1000 rows x 4 columns]

In [ ]:
df['score_real'].value_counts()

score_real
0    729
1    271
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(tfidf, df['score_real'], test_size=0.2, random_state=10, stratify=df['score_real'])


800
200


In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=10)
model.fit(X_train, y_train)

LogisticRegression(random_state=10)

In [ ]:
model.coef_

array([[ 0.2452829 ,  0.1607844 ,  0.1333321 , ..., -0.0390425 ,
        -0.05159871, -0.01282677]])

In [ ]:
model.intercept_

array([-1.29621504])

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [ ]:
y_test

314    0
908    0
392    1
97     1
23     0
      ..
579    0
148    0
202    0
641    0
536    0
Name: score_real, Length: 200, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_pred, y_test)

0.78

In [ ]:
text = '메뉴가 많아서 좋아요'

def text_predict(text):
    data = re.sub(r'[^ㄱ-ㅣ가-힣\s]','',text)
    okt = Okt()
    nouns = okt.nouns(data)
    nouns = [x for x in nouns if len(x)>1]
    tfidf = tfidf_vect.transform([nouns]).toarray()
    return model.predict(tfidf)

text_predict(text)

array([1])